/**
 * Fetch Cloudflare IP ranges from official sources and write to file.
 */

const CLOUDFLARE_IPS_V4 = "https://www.cloudflare.com/ips-v4";
const CLOUDFLARE_IPS_V6 = "https://www.cloudflare.com/ips-v6";

/** Extended ranges (Xray/VPN working, not in official CDN list). */
const EXTENDED_RANGES = [
  "# Extended Cloudflare ranges (Xray/VPN working)",
  "135.84.0.0/16",
];

export async function fetchCloudflareRanges(): Promise<{
  ipv4: string[];
  ipv6: string[];
}> {
  const [v4Res, v6Res] = await Promise.all([
    fetch(CLOUDFLARE_IPS_V4, { signal: AbortSignal.timeout(15000) }),
    fetch(CLOUDFLARE_IPS_V6, { signal: AbortSignal.timeout(15000) }),
  ]);

  if (!v4Res.ok) throw new Error(`Failed to fetch IPv4: ${v4Res.status}`);
  if (!v6Res.ok) throw new Error(`Failed to fetch IPv6: ${v6Res.status}`);

  const v4Text = await v4Res.text();
  const v6Text = await v6Res.text();

  const ipv4 = v4Text
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter((s) => s && !s.startsWith("#"));

  const ipv6 = v6Text
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter((s) => s && !s.startsWith("#"));

  return { ipv4, ipv6 };
}

export function formatRangesForFile(
  ipv4: string[],
  ipv6: string[],
  includeExtended: boolean
): string {
  const lines: string[] = [
    "# Cloudflare IP ranges (from cloudflare.com/ips-v4 and /ips-v6)",
    "# Generated by CloudflareScanner -fetch",
    "",
    "# IPv4 (CDN)",
    ...ipv4,
    "",
    "# IPv6",
    ...ipv6,
  ];

  if (includeExtended) {
    lines.push("", ...EXTENDED_RANGES);
  }

  return lines.join("\n") + "\n";
}
